# Generated by Django 3.2.5 on 2021-07-21 08:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email', models.TextField()),
                ('phone', models.TextField()),
                ('address', models.TextField(null=True)),
                ('birthday', models.DateField(null=True)),
                ('password', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('last_active_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last_active_on')),
            ],
        ),
    ]
