# Generated by Django 3.2.5 on 2021-07-21 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0002_useraccesstokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodInfo',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('cycle_average', models.TextField(null=True)),
                ('period_average', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Users.patient')),
            ],
        ),
    ]
