# Generated by Django 3.2.5 on 2021-07-21 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodinfo',
            name='last_period_date',
            field=models.DateField(null=True),
        ),
    ]
