# Generated by Django 3.2.5 on 2021-07-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_periodinfo_last_period_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodinfo',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='periodinfo',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
